config/routes.rb
Motivator::Application.routes.draw do
  root to: "home#index"
  
  resources :users, only: [:index, :show, :edit, :update]

  resources :motees, only: [:index, :new, :create]

  resources :sessions, except: [:new, :create, :destroy]
  
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/motee.rb
class Motee < ActiveRecord::Base
  belongs_to :user

  validates :text, presence: { message: 'The Motee needs content!' }

  def deliver!
    update_attributes! last_sent_at: Time.now
    UserMailer.motee_notification(self).deliver
  end
end

app/models/scheduler.rb
class Scheduler
  def initialize(threshold_days)
    @threshold_days = threshold_days
  end

  def run
    User.all.each do |user|
      motee = user.motees.where(''){|motee| motee.last_sent_at.nil? || motee.last_sent_at < @threshold_days.days.ago}.first
      motee.deliver! if motee && user.motees.where('date(last_sent_at) = ?', Date.today).empty?
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name

  has_many :motees

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.image = auth['info']['image']
      end
    end
  end

  def self.find_or_create_with_omniauth(auth)
    user = User.where(:provider => auth['provider'], :uid => auth['uid'].to_s).first || create_with_omniauth(auth)

    if user.image.blank? && auth['info']['image']
      user.update_attributes! image: auth['info']['image']
    end

    user
  end

  def first_name
    name.split(' ')[0]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?
  helper_method :user_complete?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      if controller_name == 'users'
        id = params[:id]
      else
        id = params[:user_id]
      end

      @user = User.find(id)
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def user_complete?
      current_user && current_user.email.present?
    end

    def complete_user!
      redirect_to edit_user_path(current_user), alert: 'Please enter your email address.' if !user_complete?
    end

    def authenticate_user!
      if !current_user
        redirect_to root_path, :alert => 'Login please!'
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/motees_controller.rb
class MoteesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :complete_user!
  
  before_filter :set_motee, only: [:show, :edit, :update]

  def index
    @motees = current_user.motees

    redirect_to new_motee_path if @motees.empty?
  end

  def new
    @motee = Motee.new
  end

  def create
    @motee = Motee.new secure_params.merge(user_id: current_user.id)

    if @motee.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  private

  def set_motee
    @motee = current_user.motees.find params[:id]
  end

  def secure_params
    params.require(:motee).permit(:text)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_with_omniauth(auth)
    
    # Reset the session after successful login, per
    # 2.8 Session Fixation – Countermeasures:
    # http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to motees_path, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, except: [:index]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(secure_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def secure_params
    params.require(:user).permit(:email,:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.jumbotron
  h1: i.fa.fa-heart-o
  h1 Motee
  .lead Catalogue motivational messages and quotes that inspire you, and let Motee remind you that everything is awesome.
  p
    - if user_signed_in?
      a.btn.btn-lg.btn-success href="#{new_motee_path}" role="button" Hey #{current_user.first_name}, create a new Motee
    - else
      a.btn.btn-lg.btn-success href="#{signin_path}" role="button" Sign up today #{fa_icon 'facebook-square'}
.row.marketing
  .col-lg-12
    h2 What is Motee?
    p We all have quotes or mantras that inspires us. We read them and they remind us of what's important.

    p More often than not we write something important down and then never look at it again.

    p Motee fixes this by randomly sending you your inspirational messages daily, weekly, monthly, yearly.

  .col-lg-12
    h2 How does Motee work?
    p
      ol
        li #{fa_icon 'pencil'} <br/>Write down your motivations (motees).
        li #{fa_icon 'envelope-o'}<br/> We'll e-mail and/or SMS you your motees randomly and regularly.

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      
      = link_to(root_path, class: 'navbar-brand') do
        = fa_icon 'heart-o'
    
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  - if current_user.image.present?
    li: img.img-circle src='#{current_user.image}' alt='user image' width='50'
  li: a href='#{new_motee_path}' Hey #{current_user.first_name}
  li = link_to 'Logout', signout_path
- else
  li
    = link_to(signin_path) do
      | Login #{fa_icon 'facebook-square'}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) : "Motivator"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : "Motivator"}"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  body
    header
      = render 'layouts/navigation'
    
    main role="main"
      = render 'layouts/messages'
      = yield

app/views/motees/_form.html.slim
= form_for(@motee) do |f|
  = render 'shared/form_errors', f: f
  .field
    = f.text_area :text, placeholder: 'The past is a ghost, the future a dream. All we ever have is now.', rows: 10

  = f.submit "Save Motee"

app/views/motees/index.html.slim
- @motees.each do |motee|
  .row.date-rows
    .col-md-3
      .date-container
        .day
          = motee.created_at.day
        .date
          strong = motee.created_at.strftime('%A')
          br
          = motee.created_at.strftime('%B')
          br
          = motee.created_at.strftime('%Y')
      
    .col-md-9 = motee.text

app/views/motees/new.html.slim
= render 'form'

app/views/shared/_form_errors.html.slim
- if f.object.errors.any?
  #error_explanation
    - f.object.errors.full_messages.each do |msg|
      p = msg

app/views/users/edit.html.slim
h1 Please enter your email address
= form_for(@user) do |f|
  .field
    = f.label :email
    = f.text_field :email

  = f.submit "Save e-mail"